package cleanup

import (
	"context"
	"errors"
	"os"
	"path/filepath"
	"testing"
	"time"
)

func TestBuildTargetPlanFindsGeneratedAndReviewOnlyCandidates(t *testing.T) {
	root := localCleanupTempDir(t)
	mustMkdirAll(t, filepath.Join(root, ".temp"))
	mustWriteCleanupFile(t, filepath.Join(root, ".temp", "cache.bin"), "generated")
	mustWriteCleanupFile(t, filepath.Join(root, "large.bin"), "large-file")
	oldPath := filepath.Join(root, "old.txt")
	mustWriteCleanupFile(t, oldPath, "old")
	oldTime := time.Date(2026, 5, 17, 12, 0, 0, 0, time.UTC)
	if err := os.Chtimes(oldPath, oldTime, oldTime); err != nil {
		t.Fatal(err)
	}

	result, err := BuildPlan(context.Background(), PlannerOptions{
		Source:         PlanSourceTarget,
		Root:           root,
		GeneratedAt:    time.Date(2026, 5, 19, 12, 0, 0, 0, time.UTC),
		LargeFileBytes: 10,
		OldFileAge:     24 * time.Hour,
	})
	if err != nil {
		t.Fatalf("BuildPlan target: %v", err)
	}

	candidates := candidatesByCategory(result.Plan.Candidates)
	generated := candidates[CategoryTargetGenerated]
	if len(generated) != 1 {
		t.Fatalf("target-generated candidates = %d, want 1: %#v", len(generated), generated)
	}
	if !generated[0].Selected || generated[0].Risk != RiskSafeGenerated {
		t.Fatalf("target-generated candidate = %#v, want selected safe candidate", generated[0])
	}
	if generated[0].LogicalBytes <= int64(len("generated")) {
		t.Fatalf("target-generated bytes = %d, want directory subtree bytes", generated[0].LogicalBytes)
	}

	for _, id := range []CategoryID{CategoryLargeFiles, CategoryOldFiles} {
		got := candidates[id]
		if len(got) != 1 {
			t.Fatalf("%s candidates = %d, want 1: %#v", id, len(got), got)
		}
		if got[0].Selected || got[0].DefaultSelected || got[0].Risk != RiskReviewOnly {
			t.Fatalf("%s candidate = %#v, want review-only unselected", id, got[0])
		}
	}

	if result.Plan.Totals.CandidateCount != 3 || result.Plan.Totals.SelectedCount != 1 {
		t.Fatalf("totals = %#v, want 3 candidates and 1 selected", result.Plan.Totals)
	}
	assertSummary(t, result.Rows, CategoryTargetGenerated, 1, 1, RiskSafeGenerated)
	assertSummary(t, result.Rows, CategoryLargeFiles, 1, 0, RiskReviewOnly)
	assertSummary(t, result.Rows, CategoryOldFiles, 1, 0, RiskReviewOnly)
}

func TestBuildTargetPlanRefusesDangerousRoots(t *testing.T) {
	_, err := BuildPlan(context.Background(), PlannerOptions{
		Source:  PlanSourceTarget,
		Root:    "/",
		HomeDir: localCleanupTempDir(t),
	})
	if err == nil {
		t.Fatal("BuildPlan target / succeeded, want refusal")
	}
	var refusal RootRefusalError
	if !errors.As(err, &refusal) {
		t.Fatalf("error = %T %[1]v, want RootRefusalError", err)
	}
	if refusal.Path != "/" {
		t.Fatalf("refusal path = %q, want /", refusal.Path)
	}
}

func TestBuildTargetPlanMarksSymlinkGeneratedCandidateReviewOnly(t *testing.T) {
	root := localCleanupTempDir(t)
	outside := localCleanupTempDir(t)
	if err := os.Symlink(outside, filepath.Join(root, ".temp")); err != nil {
		t.Fatal(err)
	}

	result, err := BuildPlan(context.Background(), PlannerOptions{
		Source:      PlanSourceTarget,
		Root:        root,
		GeneratedAt: time.Date(2026, 5, 19, 12, 0, 0, 0, time.UTC),
		CategoryIDs: []CategoryID{CategoryTargetGenerated},
	})
	if err != nil {
		t.Fatalf("BuildPlan target symlink: %v", err)
	}
	if len(result.Plan.Candidates) != 1 {
		t.Fatalf("candidates = %d, want 1", len(result.Plan.Candidates))
	}
	candidate := result.Plan.Candidates[0]
	if candidate.Identity.Kind != CandidateKindSymlink {
		t.Fatalf("candidate kind = %s, want symlink", candidate.Identity.Kind)
	}
	if candidate.Selected || candidate.DefaultSelected || candidate.Risk != RiskReviewOnly {
		t.Fatalf("symlink candidate = %#v, want unselected review-only", candidate)
	}
}

func TestBuildXcodePlanMarksArchivesReviewOnly(t *testing.T) {
	home := localCleanupTempDir(t)
	derived := filepath.Join(home, "Library", "Developer", "Xcode", "DerivedData", "App-abc")
	archive := filepath.Join(home, "Library", "Developer", "Xcode", "Archives", "2026-05-19", "App.xcarchive")
	mustMkdirAll(t, derived)
	mustWriteCleanupFile(t, filepath.Join(derived, "index"), "index")
	mustMkdirAll(t, archive)
	mustWriteCleanupFile(t, filepath.Join(archive, "Info.plist"), "archive")

	result, err := BuildPlan(context.Background(), PlannerOptions{
		Source:      PlanSourceXcode,
		HomeDir:     home,
		GeneratedAt: time.Date(2026, 5, 19, 12, 0, 0, 0, time.UTC),
	})
	if err != nil {
		t.Fatalf("BuildPlan xcode: %v", err)
	}

	candidates := candidatesByCategory(result.Plan.Candidates)
	if got := candidates[CategoryXcodeDerivedData]; len(got) != 1 || !got[0].Selected || got[0].Risk != RiskSafeGenerated {
		t.Fatalf("derived candidates = %#v, want one selected safe candidate", got)
	}
	if got := candidates[CategoryXcodeArchives]; len(got) != 1 || got[0].Selected || got[0].Risk != RiskReviewOnly {
		t.Fatalf("archive candidates = %#v, want one unselected review-only candidate", got)
	}
}

func TestBuildPlanIsDeterministicForFixtures(t *testing.T) {
	root := localCleanupTempDir(t)
	mustMkdirAll(t, filepath.Join(root, ".temp"))
	mustWriteCleanupFile(t, filepath.Join(root, ".temp", "cache.bin"), "generated")
	generatedAt := time.Date(2026, 5, 19, 12, 0, 0, 0, time.UTC)

	first, err := BuildPlan(context.Background(), PlannerOptions{
		Source:      PlanSourceTarget,
		Root:        root,
		GeneratedAt: generatedAt,
		CategoryIDs: []CategoryID{CategoryTargetGenerated},
	})
	if err != nil {
		t.Fatalf("BuildPlan first: %v", err)
	}
	second, err := BuildPlan(context.Background(), PlannerOptions{
		Source:      PlanSourceTarget,
		Root:        root,
		GeneratedAt: generatedAt,
		CategoryIDs: []CategoryID{CategoryTargetGenerated},
	})
	if err != nil {
		t.Fatalf("BuildPlan second: %v", err)
	}
	if first.Plan.PlanHash != second.Plan.PlanHash {
		t.Fatalf("plan hashes differ: %s != %s", first.Plan.PlanHash, second.Plan.PlanHash)
	}
	if first.Plan.Candidates[0].ID != second.Plan.Candidates[0].ID {
		t.Fatalf("candidate IDs differ: %s != %s", first.Plan.Candidates[0].ID, second.Plan.Candidates[0].ID)
	}
}

func candidatesByCategory(candidates []Candidate) map[CategoryID][]Candidate {
	out := make(map[CategoryID][]Candidate)
	for _, candidate := range candidates {
		out[candidate.CategoryID] = append(out[candidate.CategoryID], candidate)
	}
	return out
}

func assertSummary(t *testing.T, rows []CategorySummary, id CategoryID, candidates int, selected int, risk RiskLevel) {
	t.Helper()
	for _, row := range rows {
		if row.ID != id {
			continue
		}
		if row.CandidateCount != candidates || row.SelectedCount != selected || row.Risk != risk {
			t.Fatalf("summary %s = %#v, want candidates=%d selected=%d risk=%s", id, row, candidates, selected, risk)
		}
		return
	}
	t.Fatalf("summary missing %s: %#v", id, rows)
}

func mustMkdirAll(t *testing.T, path string) {
	t.Helper()
	if err := os.MkdirAll(path, 0o700); err != nil {
		t.Fatal(err)
	}
}

func mustWriteCleanupFile(t *testing.T, path string, content string) {
	t.Helper()
	if err := os.WriteFile(path, []byte(content), 0o600); err != nil {
		t.Fatal(err)
	}
}

func localCleanupTempDir(t *testing.T) string {
	t.Helper()
	root, err := os.MkdirTemp(".", ".cleanup-test-*")
	if err != nil {
		t.Fatal(err)
	}
	abs, err := filepath.Abs(root)
	if err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() {
		if err := os.RemoveAll(abs); err != nil {
			t.Errorf("cleanup temp dir %s: %v", abs, err)
		}
	})
	return abs
}
