package cleanup

import (
	"path/filepath"
	"strings"
)

type RiskLevel string

const (
	RiskSafeGenerated RiskLevel = "safe_generated"
	RiskReviewOnly    RiskLevel = "review_only"
	RiskOutOfScope    RiskLevel = "out_of_scope"
)

type CategoryID string

const (
	CategoryXcodeDerivedData CategoryID = "xcode-derived-data"
	CategoryTargetGenerated  CategoryID = "target-generated-data"
	CategoryRotatedLogs      CategoryID = "rotated-user-logs"

	CategoryDownloads          CategoryID = "downloads"
	CategoryLargeFiles         CategoryID = "large-files"
	CategoryOldFiles           CategoryID = "old-files"
	CategoryAppCaches          CategoryID = "app-caches"
	CategoryIOSBackups         CategoryID = "ios-device-backups"
	CategoryXcodeArchives      CategoryID = "xcode-archives"
	CategoryXcodeDeviceSupport CategoryID = "xcode-device-support"
	CategoryXcodeSimulators    CategoryID = "xcode-simulators"

	CategoryMalwareScanning          CategoryID = "malware-scanning"
	CategoryRAMCleaning              CategoryID = "ram-cleaning"
	CategoryForcedPurgeableCleanup   CategoryID = "forced-purgeable-cleanup"
	CategoryAppUninstallLeftovers    CategoryID = "app-uninstall-leftovers"
	CategoryBrowserPrivacyCleanup    CategoryID = "browser-privacy-cleanup"
	CategoryAttachmentCleanup        CategoryID = "attachment-cleanup"
	CategoryLanguageStripping        CategoryID = "language-stripping"
	CategoryBinaryThinning           CategoryID = "binary-thinning"
	CategoryAutomaticDuplicateDelete CategoryID = "automatic-duplicate-deletion"
)

type RootScope string

const (
	RootScopeHome           RootScope = "home"
	RootScopeExplicitTarget RootScope = "explicit_target"
	RootScopeVirtual        RootScope = "virtual"
)

type RootSpec struct {
	Path                   string
	Scope                  RootScope
	Recursive              bool
	RequiresExplicitTarget bool
}

type Category struct {
	ID              CategoryID
	Title           string
	Risk            RiskLevel
	DefaultSelected bool
	Summary         string
	Reason          string
	Roots           []RootSpec
	Patterns        []string
	MinimumAgeDays  int
}

type Policy struct {
	Version    string
	Categories []Category
	Safety     RootSafetyPolicy
}

type DangerousRoot struct {
	Path              string
	Reason            string
	RejectDescendants bool
}

type ExternalVolumePolicy struct {
	Root                               string
	RefuseVolumesRoot                  bool
	RefuseVolumeMountRoots             bool
	AllowChildPaths                    bool
	RequireExplicitTargetForChildPaths bool
	ChildPathRequirements              []string
}

type RootSafetyPolicy struct {
	DangerousRoots             []DangerousRoot
	ExternalVolumes            ExternalVolumePolicy
	RefuseSymlinkRoots         bool
	RefuseSymlinkCandidates    bool
	RequireRealpathContainment bool
	RequireUserOwnedRoots      bool
	RequireUserOwnedCandidates bool
}

type RootDecision struct {
	Path                        string
	Allowed                     bool
	Dangerous                   bool
	Reason                      string
	ExternalVolumeChild         bool
	RequiresExplicitTarget      bool
	RequiresOwnershipCheck      bool
	RequiresSymlinkCheck        bool
	RequiresRealpathContainment bool
}

func DefaultPolicy() Policy {
	return Policy{
		Version:    CategoryPolicyVersion,
		Categories: DefaultCategories(),
		Safety:     DefaultRootSafetyPolicy(),
	}
}

func DefaultCategories() []Category {
	categories := make([]Category, 0, len(SafeGeneratedCategories())+len(ReviewOnlyCategories())+len(OutOfScopeCategories()))
	categories = append(categories, SafeGeneratedCategories()...)
	categories = append(categories, ReviewOnlyCategories()...)
	categories = append(categories, OutOfScopeCategories()...)
	return categories
}

func SafeGeneratedCategories() []Category {
	return []Category{
		{
			ID:              CategoryXcodeDerivedData,
			Title:           "Xcode DerivedData",
			Risk:            RiskSafeGenerated,
			DefaultSelected: true,
			Summary:         "Generated Xcode build, index, and intermediate project data.",
			Reason:          "Xcode can regenerate DerivedData. This category excludes Archives, DeviceSupport, documentation, and simulators.",
			Roots: []RootSpec{
				{Path: "~/Library/Developer/Xcode/DerivedData", Scope: RootScopeHome, Recursive: true},
			},
		},
		{
			ID:              CategoryTargetGenerated,
			Title:           "Target-local generated data",
			Risk:            RiskSafeGenerated,
			DefaultSelected: true,
			Summary:         "Allowlisted build and tool caches inside an explicit target folder.",
			Reason:          "These paths are generated by build/test tools and are only eligible inside a user-provided target root that passes safety checks.",
			Roots: []RootSpec{
				{Path: "<target>", Scope: RootScopeExplicitTarget, Recursive: true, RequiresExplicitTarget: true},
			},
			Patterns: []string{
				".temp",
				".build",
				"build",
				"dist",
				".dart_tool",
				"node_modules/.cache",
				".pytest_cache",
				".mypy_cache",
				".ruff_cache",
				"coverage",
				"DerivedData",
			},
		},
		{
			ID:              CategoryRotatedLogs,
			Title:           "Old rotated user logs",
			Risk:            RiskSafeGenerated,
			DefaultSelected: true,
			Summary:         "Rotated or compressed logs in user-owned log directories after an age threshold.",
			Reason:          "Old rotated logs are generated diagnostics and are lower value than active logs; active logs are not included.",
			Roots: []RootSpec{
				{Path: "~/Library/Logs", Scope: RootScopeHome, Recursive: true},
			},
			Patterns: []string{
				"*.log.[0-9]*",
				"*.log.*.gz",
				"*.log.*.bz2",
				"*.log.*.xz",
				"*.log.*.zip",
				"*.old",
			},
			MinimumAgeDays: 14,
		},
	}
}

func ReviewOnlyCategories() []Category {
	return []Category{
		{
			ID:              CategoryDownloads,
			Title:           "Downloads",
			Risk:            RiskReviewOnly,
			DefaultSelected: false,
			Summary:         "Files in the user's Downloads folder.",
			Reason:          "Downloads often contain intentionally saved user data and must be selected by the user.",
			Roots: []RootSpec{
				{Path: "~/Downloads", Scope: RootScopeHome, Recursive: true},
			},
		},
		{
			ID:              CategoryLargeFiles,
			Title:           "Large files",
			Risk:            RiskReviewOnly,
			DefaultSelected: false,
			Summary:         "Large user files discovered by size heuristics.",
			Reason:          "Size does not imply disposable data; deletion requires human review.",
			Roots: []RootSpec{
				{Path: "<scan-result>", Scope: RootScopeVirtual, Recursive: false},
			},
		},
		{
			ID:              CategoryOldFiles,
			Title:           "Old files",
			Risk:            RiskReviewOnly,
			DefaultSelected: false,
			Summary:         "Old user files discovered by age heuristics.",
			Reason:          "Age does not imply disposable data; deletion requires human review.",
			Roots: []RootSpec{
				{Path: "<scan-result>", Scope: RootScopeVirtual, Recursive: false},
			},
		},
		{
			ID:              CategoryAppCaches,
			Title:           "App caches",
			Risk:            RiskReviewOnly,
			DefaultSelected: false,
			Summary:         "Application caches under the user's Library.",
			Reason:          "App caches can contain offline state, account state, expensive regenerated data, or app-specific semantics.",
			Roots: []RootSpec{
				{Path: "~/Library/Caches", Scope: RootScopeHome, Recursive: true},
			},
		},
		{
			ID:              CategoryIOSBackups,
			Title:           "iOS device backups",
			Risk:            RiskReviewOnly,
			DefaultSelected: false,
			Summary:         "Local iPhone and iPad backups.",
			Reason:          "Backups protect user data and may be the only recovery copy.",
			Roots: []RootSpec{
				{Path: "~/Library/Application Support/MobileSync/Backup", Scope: RootScopeHome, Recursive: true},
			},
		},
		{
			ID:              CategoryXcodeArchives,
			Title:           "Xcode Archives",
			Risk:            RiskReviewOnly,
			DefaultSelected: false,
			Summary:         "Archived builds produced by Xcode.",
			Reason:          "Archives can be needed for distribution, dSYM symbolication, or release reproducibility.",
			Roots: []RootSpec{
				{Path: "~/Library/Developer/Xcode/Archives", Scope: RootScopeHome, Recursive: true},
			},
		},
		{
			ID:              CategoryXcodeDeviceSupport,
			Title:           "Xcode DeviceSupport",
			Risk:            RiskReviewOnly,
			DefaultSelected: false,
			Summary:         "Device support files installed for connected devices.",
			Reason:          "DeviceSupport may be needed for debugging or symbolication on specific OS/device combinations.",
			Roots: []RootSpec{
				{Path: "~/Library/Developer/Xcode/DeviceSupport", Scope: RootScopeHome, Recursive: true},
				{Path: "~/Library/Developer/Xcode/iOS DeviceSupport", Scope: RootScopeHome, Recursive: true},
			},
		},
		{
			ID:              CategoryXcodeSimulators,
			Title:           "Xcode simulators",
			Risk:            RiskReviewOnly,
			DefaultSelected: false,
			Summary:         "Installed simulator devices and their data.",
			Reason:          "Simulators contain runtimes, installed apps, and test data; deletion can disrupt development workflows.",
			Roots: []RootSpec{
				{Path: "~/Library/Developer/CoreSimulator/Devices", Scope: RootScopeHome, Recursive: true},
			},
		},
	}
}

func OutOfScopeCategories() []Category {
	return []Category{
		{
			ID:              CategoryMalwareScanning,
			Title:           "Malware scanning",
			Risk:            RiskOutOfScope,
			DefaultSelected: false,
			Summary:         "Security scanning and malware removal.",
			Reason:          "Malware detection needs a separate threat model, signatures, update flow, and review process.",
		},
		{
			ID:              CategoryRAMCleaning,
			Title:           "RAM cleaning",
			Risk:            RiskOutOfScope,
			DefaultSelected: false,
			Summary:         "Forcing memory pressure or cache eviction.",
			Reason:          "RAM cleaning is not disk cleanup and can degrade system behavior.",
		},
		{
			ID:              CategoryForcedPurgeableCleanup,
			Title:           "Forced purgeable-space cleanup",
			Risk:            RiskOutOfScope,
			DefaultSelected: false,
			Summary:         "Forcing macOS/APFS purgeable storage reclamation.",
			Reason:          "Purgeable storage is managed asynchronously by macOS; forced reclamation is not part of v1.",
		},
		{
			ID:              CategoryAppUninstallLeftovers,
			Title:           "App uninstall leftovers",
			Risk:            RiskOutOfScope,
			DefaultSelected: false,
			Summary:         "Finding and deleting files associated with removed applications.",
			Reason:          "App leftovers need app-specific ownership matching and review; name-only matching is unsafe.",
		},
		{
			ID:              CategoryBrowserPrivacyCleanup,
			Title:           "Browser privacy cleanup",
			Risk:            RiskOutOfScope,
			DefaultSelected: false,
			Summary:         "Browser history, cookies, profiles, and privacy data.",
			Reason:          "Browser cleanup has app-specific privacy semantics and account consequences.",
		},
		{
			ID:              CategoryAttachmentCleanup,
			Title:           "Mail, browser, and chat attachments",
			Risk:            RiskOutOfScope,
			DefaultSelected: false,
			Summary:         "Attachment stores managed by mail, browser, and chat applications.",
			Reason:          "Attachments need app-specific recovery semantics and modified-file handling.",
		},
		{
			ID:              CategoryLanguageStripping,
			Title:           "Language stripping",
			Risk:            RiskOutOfScope,
			DefaultSelected: false,
			Summary:         "Removing app localization resources.",
			Reason:          "Language stripping mutates installed apps and can break signatures or updates.",
		},
		{
			ID:              CategoryBinaryThinning,
			Title:           "Binary thinning",
			Risk:            RiskOutOfScope,
			DefaultSelected: false,
			Summary:         "Removing binary slices or other executable resources.",
			Reason:          "Binary thinning mutates installed binaries and can break signatures or updates.",
		},
		{
			ID:              CategoryAutomaticDuplicateDelete,
			Title:           "Automatic duplicate deletion",
			Risk:            RiskOutOfScope,
			DefaultSelected: false,
			Summary:         "Automatically deleting files that look duplicated.",
			Reason:          "Duplicate detection cannot infer which copy is canonical without explicit user choice.",
		},
	}
}

func DefaultSelectedCategoryIDs() []CategoryID {
	var ids []CategoryID
	for _, category := range DefaultCategories() {
		if category.DefaultSelected {
			ids = append(ids, category.ID)
		}
	}
	return ids
}

func DefaultRootSafetyPolicy() RootSafetyPolicy {
	return RootSafetyPolicy{
		DangerousRoots: []DangerousRoot{
			{Path: "/", Reason: "filesystem root is never a cleanup target"},
			{Path: "$HOME", Reason: "home root contains mixed user data; use narrower categories or explicit child targets"},
			{Path: "/Users", Reason: "all-user home root can include other users and user data"},
			{Path: "/System", Reason: "system-managed root", RejectDescendants: true},
			{Path: "/Library", Reason: "system and shared app support root", RejectDescendants: true},
			{Path: "/Applications", Reason: "installed applications root", RejectDescendants: true},
			{Path: "/bin", Reason: "system executable root", RejectDescendants: true},
			{Path: "/sbin", Reason: "system executable root", RejectDescendants: true},
			{Path: "/usr", Reason: "system executable and support root", RejectDescendants: true},
			{Path: "/private", Reason: "system private storage root", RejectDescendants: true},
			{Path: "/var", Reason: "system variable storage root", RejectDescendants: true},
			{Path: "/Volumes", Reason: "external volume mount root"},
		},
		ExternalVolumes: ExternalVolumePolicy{
			Root:                               "/Volumes",
			RefuseVolumesRoot:                  true,
			RefuseVolumeMountRoots:             true,
			AllowChildPaths:                    true,
			RequireExplicitTargetForChildPaths: true,
			ChildPathRequirements: []string{
				"must be an explicit user-provided target",
				"must not be the mounted volume root",
				"root and candidates must be owned by the current user",
				"root and candidates must not be symlinks",
				"candidate real paths must remain contained within the root real path",
			},
		},
		RefuseSymlinkRoots:         true,
		RefuseSymlinkCandidates:    true,
		RequireRealpathContainment: true,
		RequireUserOwnedRoots:      true,
		RequireUserOwnedCandidates: true,
	}
}

func (policy RootSafetyPolicy) EvaluateRoot(path string, homeDir string) RootDecision {
	cleanPath := filepath.Clean(path)
	decision := RootDecision{
		Path:                        cleanPath,
		Allowed:                     true,
		RequiresOwnershipCheck:      policy.RequireUserOwnedRoots,
		RequiresSymlinkCheck:        policy.RefuseSymlinkRoots,
		RequiresRealpathContainment: policy.RequireRealpathContainment,
	}

	if dangerous, ok := policy.matchDangerousRoot(cleanPath, homeDir); ok {
		decision.Allowed = false
		decision.Dangerous = true
		decision.Reason = dangerous.Reason
		return decision
	}

	volumeRoot := filepath.Clean(policy.ExternalVolumes.Root)
	if policy.ExternalVolumes.RefuseVolumesRoot && cleanPath == volumeRoot {
		decision.Allowed = false
		decision.Dangerous = true
		decision.Reason = "external volume mount root is never a cleanup target"
		return decision
	}

	if volumeName, rest, ok := splitExternalVolumePath(cleanPath, volumeRoot); ok {
		if policy.ExternalVolumes.RefuseVolumeMountRoots && rest == "" {
			decision.Allowed = false
			decision.Dangerous = true
			decision.Reason = "external volume root " + volumeName + " is never default-selected or cleaned as a whole"
			return decision
		}

		decision.ExternalVolumeChild = true
		decision.RequiresExplicitTarget = policy.ExternalVolumes.RequireExplicitTargetForChildPaths
		if !policy.ExternalVolumes.AllowChildPaths {
			decision.Allowed = false
			decision.Dangerous = true
			decision.Reason = "external volume child paths are disabled by policy"
		}
	}

	return decision
}

func (policy RootSafetyPolicy) matchDangerousRoot(path string, homeDir string) (DangerousRoot, bool) {
	cleanHome := filepath.Clean(homeDir)
	for _, root := range policy.DangerousRoots {
		if root.Path == "$HOME" {
			if homeDir != "" && path == cleanHome {
				return root, true
			}
			continue
		}
		rootPath := filepath.Clean(root.Path)
		if path == rootPath || root.RejectDescendants && hasPathPrefix(path, rootPath) {
			return root, true
		}
	}
	return DangerousRoot{}, false
}

func hasPathPrefix(path string, root string) bool {
	if root == string(filepath.Separator) {
		return false
	}
	return strings.HasPrefix(path, root+string(filepath.Separator))
}

func splitExternalVolumePath(path string, volumeRoot string) (volumeName string, rest string, ok bool) {
	prefix := volumeRoot + string(filepath.Separator)
	if !strings.HasPrefix(path, prefix) {
		return "", "", false
	}

	remaining := strings.TrimPrefix(path, prefix)
	parts := strings.SplitN(remaining, string(filepath.Separator), 2)
	if parts[0] == "" {
		return "", "", false
	}
	if len(parts) == 1 {
		return parts[0], "", true
	}
	return parts[0], parts[1], true
}
